### ISSUE TITLE
MFC build fails on MacOS due to attempting to fetch aarch64 cmake

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC#31]
MFC build fails on MacOS due to attempting to fetch aarch64 cmake
```
[I]shb-m1pro: Downloads/MFC $ ./mfc.sh build -j 1
Traceback (most recent call last):
  File "/opt/homebrew/bin/cmake", line 8, in <module>
    sys.exit(cmake())
  File "/opt/homebrew/lib/python3.10/site-packages/cmake/__init__.py", line 46, in cmake
    raise SystemExit(_program('cmake', sys.argv[1:]))
  File "/opt/homebrew/lib/python3.10/site-packages/cmake/__init__.py", line 42, in _program
    return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/lib/python3.10/site-packages/cmake/data/CMake.app/Contents/bin/cmake'
[mfc.sh]: CMake is out of date (current:  < minimum: 3.18).
[mfc.sh]: Downloading CMake v3.24.2 for arm64 from https://github.com/Kitware/CMake.
--2022-10-28 21:29:09--  https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-arm64.sh
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-28 21:29:09 ERROR 404: Not Found.

[mfc.sh]: Error: Failed to download a compatible version of CMake.
CMake is not discoverable or is an older release, incompatible with MFC. Please download
or install a recent version of CMake to get past this step. If you are currently on a
managed system like a cluster, provided there is no suitable environment module, you can
either build it from source, or get it via Spack.
- The minimum required version is currently CMake v3.18.0.
- We attempted to download CMake v3.24.2 from https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-arm64.sh.
```

**Comment by henryleberre** [comment]
CMake does provide a shell script for installation on  `aarch64` (e.i `amd64`) Linux but they aren't compatible with a macOS environment. We now produce an error on macOS when attempting to download CMake, giving adequate instructions to install it manually (via `homebrew`, `module`, `apt`, `pacman`, `spack`, ...). This is the same (generic) error message that appears when failing to download/install on any other system.

I also noticed that `mfc.sh`'s text coloring doesn't work and was able to fix it with this workaround:

```bash
if [ -t 1 ]; then
    RED="\x1B[31m";    CYAN="\x1B[36m";    GREEN="\x1B[32m"
    YELLOW="\x1B[33m"; MAGENTA="\x1B[35m"; COLOR_RESET="\033[m"
fi

log()     { echo -e "$CYAN"mfc"$COLOR_RESET: $1$COLOR_RESET"; }
ok()      { log "$GREEN""OK$COLOR_RESET > $1";                }
warning() { log "$YELLOW""WARNING$COLOR_RESET > $1";          }
error()   { log "$RED""ERROR$COLOR_RESET > $1";               }
```

**Comment by sbryngelson** [comment]
Cool, is there a PR for this (soon, I take it?)

**Comment by henryleberre** [comment]
Yes I will submit a PR once I verify I this still works on other systems.
